name = "gpr_rust"
description = "Dependencies for the gpr-rust Rust crate."
version = "0.1.0-dev"

authors = ["Johannes Kliemann"]
maintainers = ["Johannes Kliemann <jk@jkliemann.de>"]
maintainers-logins = ["jklmnn"]
[[depends-on]]
gnatcoll = "^24.0.0"
gnatcoll_gmp = "^24.0.0"
gnatcoll_iconv = "^24.0.0"
xmlada = "^24.0.0"
