name: Tests

on:
  push:
  schedule:
    - cron: "0 4 * * *"


jobs:
  build_and_test:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - name: Install Ada toolchain
        uses: alire-project/setup-alire@v4
      - name: Install python dependencies
        run: |
          python -m pip install --upgrade pip wheel virtualenv
      - name: Tests
        run: |
          alr -q printenv --unix
          eval $(alr -q printenv --unix)
          cargo fmt -- --check
          cargo clippy -- -Dwarnings
          cargo test
      - name: Examples
        working-directory: examples/ada_hello
        run: |
          eval $(alr printenv --unix)
          export LD_LIBRARY_PATH=$(pwd)/ada_hello/lib
          cargo run
  build_and_test_nightly:
    name: Tests (nightly toolchain)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
      - name: Install Ada toolchain
        uses: alire-project/setup-alire@v4
        with:
          version: nightly
      - name: Install python dependencies
        run: |
          python -m pip install --upgrade pip wheel virtualenv
      - name: Tests
        run: |
          alr -q printenv --unix
          eval $(alr -q printenv --unix)
          cargo fmt -- --check
          cargo clippy -- -Dwarnings
          cargo test
      - name: Examples
        working-directory: examples/ada_hello
        run: |
          eval $(alr printenv --unix)
          export LD_LIBRARY_PATH=$(pwd)/ada_hello/lib
          cargo run
