name: Tests

on: [push]

jobs:
  build_and_test:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - name: Install Ada toolchain
        uses: ada-actions/toolchain@ce2021
        with:
          distrib: community
      - name: Install python dependencies
        run: |
          python -m pip install --upgrade pip wheel virtualenv
      - name: Tests
        run: |
          cargo fmt -- --check
          cargo clippy -- -Dwarnings
          cargo test
      - name: Examples
        working-directory: examples/ada_hello
        run: |
          export LD_LIBRARY_PATH=$(pwd)/ada_hello/lib
          cargo run
